version: '3'
services:
  influxdb:
    image: docker.io/influxdb:1.8
    networks:
      - backend
    ports:
      - ${DB_PORT}:8086
    volumes:
      - ./influx_retention_policy.iql:/docker-entrypoint-initdb.d/influx_retention_policy.iql
      - ./.influxdb/:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${DB_NAME}
      - INFLUXDB_ADMIN_USER=${DB_USER}
      - INFLUXDB_ADMIN_PASSWORD=${DB_PASSWORD}
  grafana:
    image: docker.io/grafana/grafana-oss:10.3.1
    networks:
      - backend
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - PV_DB_NAME=${DB_NAME}
      - PV_DB_PASSWORD=${DB_PASSWORD}
      - PV_DB_USER=${DB_USER}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PW}
  vtelemetry:
    image: docker.io/arkonatechnologies/vtelemetry2
    networks:
      - backend
    depends_on:
      - influxdb
    environment:
      - MACHINES=${BLADES}
      - BLACKLIST='\.audio\.signals,\.output\.signals,\.user_labels,\.monitoring_objects\.audio,software_update,audio_source_slices,peak_meter'
      - WHITELIST='p_t_p,genlock,system'
      - INFLUX_API=1
      - DB_HOST=influxdb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - VERBOSITY=1
networks:
  backend:
    driver: bridge
