apiVersion: 2

datasources:
  - name: ${PV_DB_NAME}
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: true
    isDefault: true
    user: ${PV_DB_USER}
    uid: "GIQf3g9MVz"
    jsonData:
      dbName: ${PV_DB_NAME}
      httpHeaderName1: "Authorization"
    secureJsonData:
      # user: ${PV_DB_USER}
      httpHeaderValue1: "Token ${PV_DB_TOKEN}"
      password: ${PV_DB_PASSWORD}