apiVersion: 1

datasources:
  - name: ${PV_DB_NAME}
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: true
    isDefault: true
    uid: "GIQf3g9MVz"
    jsonData:
      version: InfluxQL 
      database: ${PV_DB_NAME} 
    secureJsonData:
      password: ${PV_DB_TOKEN}