{
 "title": "CPU-Services [Facility]",
 "tags": [
  "CPU",
  "Facility"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "blades",
    "query": "show tag values with key=\"ip\""
   },
   {
    "name": "processes",
    "query": "system.sysinfo.services.vmatrix_frontpanel,system.sysinfo.services.vmatrix_genlock,system.sysinfo.services.vmatrix_i2cserver,system.sysinfo.services.vmatrix_j2kdecoder,system.sysinfo.services.vmatrix_matrix,system.sysinfo.services.vmatrix_metaproc,system.sysinfo.services.vmatrix_multiviewer,system.sysinfo.services.vmatrix_neighborhood_watch,system.sysinfo.services.vmatrix_networkmgr,system.sysinfo.services.vmatrix_ptp,system.sysinfo.services.vmatrix_rtpreceiver,system.sysinfo.services.vmatrix_server,system.sysinfo.services.vmatrix_system,system.sysinfo.services.vmatrix_timeflows,system.sysinfo.services.vmatrix_udx,system.sysinfo.services.vmatrix_uploadmgr,system.sysinfo.services.vmatrix_webserver,system.sysinfo.services.rsyslog,system.sysinfo.services.snmpd,\nsystem.sysinfo.services.vm_frontpanel,system.sysinfo.services.vm_genlock,system.sysinfo.services.vm_i2cserver,system.sysinfo.services.vm_j2kdecoder,system.sysinfo.services.vm_matrix,system.sysinfo.services.vm_metaproc,system.sysinfo.services.vm_multiviewer,system.sysinfo.services.vm_neighborhood_watch,system.sysinfo.services.vm_networkmgr,system.sysinfo.services.vm_ptp,system.sysinfo.services.vm_rtpreceiver,system.sysinfo.services.vm_server,system.sysinfo.services.vm_system,system.sysinfo.services.vm_timeflows,system.sysinfo.services.vm_udx,system.sysinfo.services.vm_uploadmgr,system.sysinfo.services.vm_webserver"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$processes$/",
     "query": "from(bucket: \"vmatrix\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => contains(value: r.ip, set: ${machine:json}))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${processes}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$processes$/",
     "query": "from(bucket: \"vmatrix\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => contains(value: r.ip, set: ${machine:json}))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${processes}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.sysinfo",
     "query": "from(bucket: \"vmatrix\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => contains(value: r.ip, set: ${machine:json}))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system.sysinfo\")\n  |> filter(fn: (r) => r[\"_field\"] == \"freeram\")\n    |> toInt()\n  |> map(fn: (r) => ({\n        r with\n        _value: r._value * 1000000\n      })\n    )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "freeram" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  }
 ]
}