{
 "title": "CPU-Services [Blade]",
 "tags": [
  "CPU",
  "Blade"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "blades",
    "query": "show tag values with key=\"ip\""
   },
   {
    "name": "processes",
    "query": "system.sysinfo.services.vm_frontpanel,system.sysinfo.services.vm_genlock,system.sysinfo.services.vm_i2cserver,system.sysinfo.services.vm_j2kdecoder,system.sysinfo.services.vm_matrix,system.sysinfo.services.vm_metaproc,system.sysinfo.services.vm_multiviewer,system.sysinfo.services.vm_neighborhood_watch,system.sysinfo.services.vm_networkmgr,system.sysinfo.services.vm_ptp,system.sysinfo.services.vm_rtpreceiver,system.sysinfo.services.vm_server,system.sysinfo.services.vm_system,system.sysinfo.services.vm_timeflows,system.sysinfo.services.vm_udx,system.sysinfo.services.vm_uploadmgr,system.sysinfo.services.vm_webserver,system.sysinfo.services.snmpd,rsystem.sysinfo.services.syslog"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Clock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system.sysinfo",
     "query": "from(bucket: \"vmatrix\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system.sysinfo\")\n  |> filter(fn: (r) => r._field == \"cpu_freq\")\n  |> filter(fn: (r) => r.ip == \"${machine}\")\n  //|> filter(fn: (r) => contains(value: r.ip, set: ${machine:json}))\n  |> drop(columns: [\"_field\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1,offset:0)\n\n\n",
     "select": [
      [
       { "params": [ "cpu_freq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "alias": "sys1",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "system.partitions.system1",
     "select": [
      [
       { "params": [ "version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "sys0",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "system.partitions.system0",
     "select": [
      [
       { "params": [ "version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "boot",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "system.partitions",
     "select": [
      [
       { "params": [ "booted" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Free-RAM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Freeram ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.sysinfo",
     "query": "from(bucket: \"vmatrix\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system.sysinfo\" and r._field == \"load_avg\")\n  |> filter(fn: (r) => r.ip == \"${machine}\")\n  |> aggregateWindow(every: 10s, fn: max, createEmpty: false)\n  |> drop(columns: [\"_field\"])",
     "select": [
      [
       { "params": [ "freeram" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Load_avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.sysinfo",
     "query": "from(bucket: \"vmatrix\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system.sysinfo\" and r._field == \"load_avg\")\n  |> filter(fn: (r) => r.ip == \"${machine}\")\n  |> aggregateWindow(every: 10s, fn: max, createEmpty: false)\n  |> drop(columns: [\"_field\"])",
     "select": [
      [
       { "params": [ "load_avg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$processes$/",
     "query": "SELECT max(\"cpu_usage\") FROM \"system.sysinfo.services.vm_frontpanel\",\"system.sysinfo.services.vm_genlock\",\"system.sysinfo.services.vm_i2cserver\",\"system.sysinfo.services.vm_j2kdecoder\",\"system.sysinfo.services.vm_matrix\",\"system.sysinfo.services.vm_metaproc\",\"system.sysinfo.services.vm_multiviewer\",\"system.sysinfo.services.vm_neighborhood_watch\",\"system.sysinfo.services.vm_networkmgr\",\"system.sysinfo.services.vm_ptp\",\"system.sysinfo.services.vm_rtpreceiver\",\"system.sysinfo.services.vm_server\",\"system.sysinfo.services.vm_system\",\"system.sysinfo.services.vm_timeflows\",\"system.sysinfo.services.vm_udx\",\"system.sysinfo.services.vm_uploadmgr\",\"system.sysinfo.services.vm_webserver\",\"system.sysinfo.services.snmpd\",\"rsystem.sysinfo.services.syslog\" WHERE (\"ip\" =~ /^$blades$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$processes$/",
     "query": "from(bucket: \"vmatrix\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_frontpanel\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_genlock\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_i2cserver\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_j2kdecoder\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_matrix\" or \n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_metaproc\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_multiviewer\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_neighborhood_watch\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_networkmgr\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_ptp\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_rtpreceiver\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_server\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_system\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_timeflows\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_udx\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_uploadmgr\" or\n    r[\"_measurement\"] == \"system.sysinfo.services.vmatrix_webserver\")\n  |> filter(fn: (r) => r[\"_field\"] == \"memory_usage\")\n  |> filter(fn: (r) => r.ip == \"${machine}\")\n  |> drop(columns: [\"ip\"])\n  |> drop(columns: [\"_field\"])\n//  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\n//  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  }
 ]
}