{
 "title": "CPU-Load [Facility]",
 "tags": [
  "CPU",
  "Facility"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "blades",
    "query": "show tag values with key=\"ip\""
   }
  ]
 },
 "panels": [
  {
   "title": "CPU-Load (Latest)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system.sysinfo",
     "select": [
      [
       { "params": [ "load_avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Clock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "system.sysinfo",
     "query": "from(bucket: \"vmatrix\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system.sysinfo\")\n  |> filter(fn: (r) => r._field == \"cpu_freq\")\n  |> filter(fn: (r) => contains(value: r.ip, set: ${machines:json}))\n  |> drop(columns: [\"_field\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1,offset:0)\n\n\n",
     "select": [
      [
       { "params": [ "cpu_freq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.sysinfo",
     "query": "from(bucket: \"vmatrix\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system.sysinfo\" and r._field == \"load_avg\")\n  |> filter(fn: (r) => contains(value: r.ip, set: ${machines:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> drop(columns: [\"_field\"])\n//  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "load_avg" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  }
 ]
}