{
 "title": "EHIP/SW",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "EHIP reset timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({level=\"critical\"} |= `Timeout while waiting for EHIP reset` [10m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Link_up",
   "type": "state-timeline",
   "gridPos": { "h": 41, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "$tag_ip P$tag_ports",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip::tag" ], "type": "tag" },
      { "params": [ "ports::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports",
     "select": [
      [
       { "params": [ "link_up" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ports::tag", "operator": "=~", "value": "/0|1/" }
     ]
    }
   ]
  },
  {
   "title": "LLDP Neighbor",
   "type": "state-timeline",
   "gridPos": { "h": 51, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "alias": "$tag_ip P$tag_ports",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip::tag" ], "type": "tag" },
      { "params": [ "ports::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports.lldp_neighbors",
     "select": [
      [
       { "params": [ "system_name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ports::tag", "operator": "=~", "value": "/0|1/" }
     ]
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "state-timeline",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.hostname",
     "select": [
      [
       { "params": [ "current_configuration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Partition",
   "type": "state-timeline",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 122 },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system.partitions",
     "select": [
      [
       { "params": [ "booted" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SW Version @ Partition 0",
   "type": "state-timeline",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system.partitions.system0",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SW Version @ Partition 1",
   "type": "state-timeline",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 166 },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip::tag" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "system.partitions.system1",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}