{
 "title": "I/O",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "blades",
    "query": "show tag values with key=\"ip\""
   }
  ]
 },
 "panels": [
  {
   "title": "Egress Tracks Incoming",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": " video $tag_video_receivers",
     "groupBy": [
      { "params": [ "video_receivers" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.egress.tracks",
     "select": [
      [
       { "params": [ "incoming" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "audio $tag_audio_receivers",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "audio_receivers" ], "type": "tag" }
     ],
     "measurement": "r_t_p_receiver.audio_receivers.generic.egress.tracks",
     "select": [
      [
       { "params": [ "incoming" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "I/O Input",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "$tag_input",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "input::tag" ], "type": "tag" }
     ],
     "measurement": "i_o_module.input.sdi.output.video",
     "select": [
      [
       { "params": [ "standard" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "I/O Output",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "$tag_output",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "output" ], "type": "tag" }
     ],
     "measurement": "i_o_module.output.sdi.v_src_status",
     "select": [
      [
       { "params": [ "source" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Video Transmitters Calculated Standard",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "$tag_ip $tag_video_transmitters",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "video_transmitters" ], "type": "tag" }
     ],
     "measurement": "r_t_p_transmitter.video_transmitters.constraints",
     "select": [
      [
       { "params": [ "calculation_standard" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Video Transmitters Video Source",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "alias": "$tag_video_transmitters",
     "groupBy": [
      { "params": [ "video_transmitters" ], "type": "tag" }
     ],
     "measurement": "r_t_p_transmitter.video_transmitters.v_src_status",
     "select": [
      [
       { "params": [ "source" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP State",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "alias": " ",
     "measurement": "p_t_p_clock",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Video Receiver Std",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "alias": " $tag_video_receivers",
     "groupBy": [
      { "params": [ "video_receivers" ], "type": "tag" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.media_specific.output.video",
     "select": [
      [
       { "params": [ "standard" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "User info  Status",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "alias": " ",
     "measurement": "system.usrinfo",
     "select": [
      [
       { "params": [ "cur_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Video Transmitters IRQ Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "measurement": "video_transmitter.pool",
     "select": [
      [
       { "params": [ "error_irq_counter" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$machines$/" },
      { "condition": "OR", "key": "pool", "operator": "=", "value": "0" }
     ]
    }
   ]
  }
 ]
}