{
 "title": "Network [Blade]",
 "tags": [
  "Network",
  "PTP",
  "Genlock"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "blades",
    "query": "SHOW TAG VALUES  WITH KEY = \"ip\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Port status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "link_up (port $tag_ports)",
     "groupBy": [
      { "params": [ "ports::tag" ], "type": "tag" }
     ],
     "measurement": "network_interfaces.ports",
     "select": [
      [
       { "params": [ "link_up" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP / Genlock State",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Genlock $tag_ip #$tag_instances",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "instances" ], "type": "tag" }
     ],
     "measurement": "genlock.instances.lanes.video_f50_ish",
     "query": "SELECT \"state\" FROM \"genlock.instances.lanes.video_f50_ish\" WHERE (\"ip\" =~ /^$blades$/) AND $timeFilter GROUP BY \"ip\"",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "PTP Clock $tag_ip",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "p_t_p_clock",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Network - TX-Test IP=172.16.182.2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "TX_ST {Ports: $tag_ports}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ports::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports.aggregate_traffic_statistics.tx_st",
     "query": "SELECT last(\"packets_per_sec\") FROM \"autogen\".\"network_interfaces.ports.aggregate_traffic_statistics.tx_st\" WHERE (\"ip\"::tag =~ /^$blades$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=", "value": "172.16.182.2" }
     ]
    },
    {
     "alias": "link_up_changed_count {Ports: $tag_ports}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ports::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports",
     "select": [
      [
       { "params": [ "link_up_changed_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=", "value": "172.16.182.2" }
     ]
    }
   ]
  },
  {
   "title": "Network - RX-Test IP=172.16.180.2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "RX_ST {Ports: $tag_ports}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ports::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports.aggregate_traffic_statistics.rx_st",
     "query": "SELECT last(\"packets_per_sec\") FROM \"autogen\".\"network_interfaces.ports.aggregate_traffic_statistics.tx_st\" WHERE (\"ip\"::tag =~ /^$blades$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "packets_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=", "value": "172.16.180.2" }
     ]
    },
    {
     "alias": "link_up_changed_count {Ports: $tag_ports}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ports::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports",
     "select": [
      [
       { "params": [ "link_up_changed_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=", "value": "172.16.180.2" }
     ]
    }
   ]
  },
  {
   "title": "PTP Clock - Relative Clock Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p_t_p_clock",
     "select": [
      [
       { "params": [ "relative_clock_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "system.sysinfo",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Genlock - Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "genlock.output.offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "instances" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "genlock.instances.output.offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Network - TX All Streams (bytes/s)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 }
  },
  {
   "title": "Genlock - Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "genlock.output.drift",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "instances" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "genlock.instances.output.drift",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Network - RX Multicast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_ip [$tag_ports]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "ports" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports.aggregate_traffic_statistics.rx_multicast",
     "query": "SELECT mean(\"tx_all_streams.bytes_per_sec\")  * 8 FROM \"network_interfaces.ports.fpga_lane_statistics\" WHERE (\"ip\" =~ /^$temp_machine$/) AND $timeFilter GROUP BY time($__interval), \"ip\", \"fpga_lane_statistics_index\" fill(none)",
     "select": [
      [
       { "params": [ "bytes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  }
 ]
}