{
 "title": "Network [Facility]",
 "tags": [
  "Network",
  "PTP",
  "Genlock"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "blades",
    "query": "SHOW TAG VALUES  WITH KEY=\"ip\" "
   }
  ]
 },
 "panels": [
  {
   "title": "EHIP reset timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({level=\"critical\"} |= `Timeout while waiting for EHIP reset` [10m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "repeat": "temp_machine",
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "system.sysinfo",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "  / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Clock - State",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "p_t_p_clock",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "system.sysinfo",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Clock - Relative Clock Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p_t_p_clock",
     "select": [
      [
       { "params": [ "relative_clock_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Genlock - Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "genlock.output.offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "instances" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "genlock.instances.output.offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Genlock - Drift",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "genlock.output.drift",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "instances" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "genlock.instances.output.drift",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Network - TX All Streams (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "tx_payload_octetsok {ip: $tag_ip, ports: $tag_ports}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip::tag" ], "type": "tag" },
      { "params": [ "ports::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports.aggregate_traffic_statistics.tx_payload_octetsok",
     "query": "SELECT mean(\"tx_all_streams.bytes_per_sec\")  * 8 FROM \"network_interfaces.ports.fpga_lane_statistics\" WHERE (\"ip\" =~ /^$temp_machine$/) AND $timeFilter GROUP BY time($__interval), \"ip\", \"fpga_lane_statistics_index\" fill(none)",
     "select": [
      [
       { "params": [ "bytes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "ports::tag", "operator": "=", "value": "0" },
      { "condition": "OR", "key": "ip::tag", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "ports::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "tx_all_streams {ip: $tag_ip, ports: $tag_ports, lane: $tag_fpga_lane_statistics}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip::tag" ], "type": "tag" },
      { "params": [ "ports::tag" ], "type": "tag" },
      { "params": [ "fpga_lane_statistics::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports.fpga_lane_statistics.tx_all_streams",
     "query": "SELECT mean(\"tx_all_streams.bytes_per_sec\")  * 8 FROM \"network_interfaces.ports.fpga_lane_statistics\" WHERE (\"ip\" =~ /^$temp_machine$/) AND $timeFilter GROUP BY time($__interval), \"ip\", \"fpga_lane_statistics_index\" fill(none)",
     "select": [
      [
       { "params": [ "bytes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "ports::tag", "operator": "=", "value": "0" },
      { "condition": "OR", "key": "ip::tag", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "ports::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  { "title": "Network - RX Multicast", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 } }
 ]
}