{
 "title": "PTP [Facility]",
 "tags": [
  "PTP",
  "Facility"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "blades",
    "query": "SHOW TAG VALUES with key=\"ip\""
   },
   {
    "name": "agents",
    "query": "SHOW TAG VALUES with key=\"agents\""
   }
  ]
 },
 "panels": [
  {
   "title": "PTP / Genlock State",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Genlock $tag_ip #$tag_instances",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "instances" ], "type": "tag" }
     ],
     "measurement": "genlock.instances.lanes.video_f50_ish",
     "query": "SELECT \"state\" FROM \"genlock.instances.lanes.video_f50_ish\" WHERE (\"ip\" =~ /^$blades$/) AND $timeFilter GROUP BY \"ip\"",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "PTP Clock $tag_ip",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "p_t_p_clock",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "GPS Time rx",
   "type": "timeseries",
   "description": "don't try to interpret these curves, this panel is just meant to check whether we've lost the GPS signal",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "minutes $tag_ip/$tag_gps_receivers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "gps_receivers" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "master_clock.gps_receivers.time_of_day",
     "select": [
      [
       { "params": [ "minutes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "seconds $tag_ip/$tag_gps_receivers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "gps_receivers" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "master_clock.gps_receivers.time_of_day",
     "select": [
      [
       { "params": [ "seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Clock - Relative Clock Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p_t_p_clock",
     "select": [
      [
       { "params": [ "relative_clock_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Agent - drift",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": " Agent $tag_agents @ $tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "agents" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p_t_p_flows.agents.output.drift",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "agents", "operator": "=~", "value": "/^$agents$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Agent - offset",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_ip/agent $tag_agents",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agents" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p_t_p_flows.agents.output.offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Message rates (10s derivative) [heavy]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "syncs received $tag_ip/agent $tag_agents",
     "groupBy": [
      { "params": [ "agents" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "p_t_p_flows.agents.slave_statistics",
     "select": [
      [
       { "params": [ "num_syncs_received" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "agents", "operator": "=~", "value": "/^$agents$/" }
     ]
    },
    {
     "alias": "num sync $tag_ip/agent $tag_agents",
     "groupBy": [
      { "params": [ "agents" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "p_t_p_flows.agents.slave_statistics",
     "select": [
      [
       { "params": [ "num_sync_measurements" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "agents", "operator": "=~", "value": "/^$agents$/" }
     ]
    },
    {
     "alias": "num delayres rec $tag_ip/agent $tag_agents",
     "groupBy": [
      { "params": [ "agents" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "p_t_p_flows.agents.slave_statistics",
     "select": [
      [
       { "params": [ "num_delayresps_received" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "agents", "operator": "=~", "value": "/^$agents$/" }
     ]
    },
    {
     "alias": "num delay $tag_ip/agent $tag_agents",
     "groupBy": [
      { "params": [ "agents" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "p_t_p_flows.agents.slave_statistics",
     "select": [
      [
       { "params": [ "num_delay_measurements" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "agents", "operator": "=~", "value": "/^$agents$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Message counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "syncs received $tag_ip/agent $tag_agents",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agents" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p_t_p_flows.agents.slave_statistics",
     "select": [
      [
       { "params": [ "num_syncs_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "agents", "operator": "=~", "value": "/^$agents$/" }
     ]
    },
    {
     "alias": "num syncs $tag_ip/agent $tag_agents",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agents" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p_t_p_flows.agents.slave_statistics",
     "select": [
      [
       { "params": [ "num_sync_measurements" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "agents", "operator": "=~", "value": "/^$agents$/" }
     ]
    },
    {
     "alias": "num delayres received $tag_ip/agent $tag_agents",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agents" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p_t_p_flows.agents.slave_statistics",
     "select": [
      [
       { "params": [ "num_delayresps_received" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" },
      { "condition": "AND", "key": "agents", "operator": "=~", "value": "/^$agents$/" }
     ]
    }
   ]
  }
 ]
}