{
 "title": "RTP",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "IP",
    "label": "IP",
    "query": "SHOW TAG VALUES with key=\"ip\""
   }
  ]
 },
 "panels": [
  {
   "title": "Redundancy",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Audio RX $tag_audio_receivers Redundancy ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "audio_receivers::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.audio_receivers.generic.redundancy_levels.nominally_present",
     "select": [
      [
       { "params": [ "overall" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Video RX $tag_video_receivers Redundancy ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "video_receivers::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.redundancy_levels.nominally_present",
     "select": [
      [
       { "params": [ "overall" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Stream RX Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "packet_streams::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.packet_streams.traffic_stats",
     "select": [
      [
       { "params": [ "bytes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Delay",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Video RX $tag_video_receivers ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "video_receivers::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.timing.read_delay.overall",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Audio RX $tag_audio_receivers ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "audio_receivers::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.audio_receivers.generic.timing.read_delay.overall",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Phase Offset",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "video_receivers::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.timing.current_phase.offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "audio_receivers::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.audio_receivers.generic.timing.current_phase.offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Video Standard",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "alias": "RX $tag_video_receivers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "video_receivers::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.media_specific.output.video",
     "select": [
      [
       { "params": [ "standard" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  }
 ]
}