{
 "title": "SDI Input [Blade]",
 "tags": [
  "Blade",
  "SDI"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "blades",
    "query": "SHOW TAG VALUES WITH KEY=\"ip\""
   }
  ]
 },
 "panels": [
  {
   "title": "SDI Input - Standard",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "input #$tag_input",
     "groupBy": [
      { "params": [ "input" ], "type": "tag" }
     ],
     "measurement": "i_o_module.input.sdi.hw_status",
     "select": [
      [
       { "params": [ "standard" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "SDI Input Mode",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "input #$tag_input",
     "groupBy": [
      { "params": [ "input" ], "type": "tag" }
     ],
     "measurement": "i_o_module.input.sdi",
     "select": [
      [
       { "params": [ "mode" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "SDI Input Offset to PTP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "SDI Input #$tag_input",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "input" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "i_o_module.input.sdi.output.video.media_clock.offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "SDI Input Drift to FC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "SDI Input#$tag_input",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "input" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "i_o_module.input.sdi.output.video.media_clock.drift",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "SDI Input Deembedder Read Overflow",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "alias": "input $tag_input",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "input" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "i_o_module.input.sdi.hw_status",
     "select": [
      [
       { "params": [ "deemb_read_overflow" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SDI Input Deembedder Read Underflow",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "alias": "input $tag_input",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "input" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "i_o_module.input.sdi.hw_status",
     "select": [
      [
       { "params": [ "deemb_read_underflow" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SDI Input Phy RX Locked To Data",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "alias": "input #$tag_input",
     "groupBy": [
      { "params": [ "input" ], "type": "tag" }
     ],
     "measurement": "i_o_module.input.sdi.hw_status",
     "select": [
      [
       { "params": [ "phy_rx_locked_to_data" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "SDI Input Phy RX Locked To Ref",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "alias": "input #$tag_input",
     "groupBy": [
      { "params": [ "input" ], "type": "tag" }
     ],
     "measurement": "i_o_module.input.sdi.hw_status",
     "select": [
      [
       { "params": [ "phy_rx_locked_to_ref" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "SDI Input Phy Rx Calibrate Busy",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "alias": "input #$tag_input",
     "groupBy": [
      { "params": [ "input" ], "type": "tag" }
     ],
     "measurement": "i_o_module.input.sdi.hw_status",
     "select": [
      [
       { "params": [ "phy_rx_calibrate_busy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  }
 ]
}