{
 "title": "Sysinfo  [Blade]",
 "tags": [
  "Blade",
  "Sysinfo"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "blades",
    "query": "SHOW TAG VALUES WITH KEY=\"ip\""
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 } },
  { "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 } },
  { "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 } },
  { "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 } },
  {
   "title": "Frame Serial",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Frame Serial",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "system.frame.info",
     "select": [
      [
       { "params": [ "serial" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  { "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 } },
  { "gridPos": { "h": 4, "w": 3, "x": 16, "y": 1 } },
  { "gridPos": { "h": 4, "w": 3, "x": 19, "y": 1 } },
  { "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 } },
  { "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Temp / Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  { "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 } },
  { "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 } },
  { "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU / RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    { "title": "CPU Load", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 } },
    { "title": "Free RAM", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 } }
   ]
  },
  {
   "title": "Uptime / Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    { "title": "Uptime", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 } },
    {
     "title": "Corrected ECC Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "system.ecc.cpu_internal",
       "query": "from(bucket: \"vmatrix\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system.ecc.cpu_memory\" and r._field == \"ce_count\")\n  |> filter(fn: (r) => contains(value: r.ip, set: ${machines:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> drop(columns: [\"_field\"])",
       "select": [
        [
         { "params": [ "ce_count" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
       ]
      }
     ]
    },
    { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 18, "w": 6, "x": 18, "y": 13 } },
    {
     "title": "Uncorrected ECC Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 18, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_ip",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "ip" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "system.ecc.cpu_memory",
       "query": "from(bucket: \"vmatrix\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system.ecc.cpu_memory\" and r._field == \"ue_count\")\n  |> filter(fn: (r) => contains(value: r.ip, set: ${machines:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> drop(columns: [\"_field\"])",
       "select": [
        [
         { "params": [ "ue_count" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}