{
 "title": "Timing",
 "description": "Generic Dashboard for PTP/Genlock and related stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "IP",
    "label": "IP",
    "query": "SHOW TAG VALUES with key=\"ip\""
   }
  ]
 },
 "panels": [
  {
   "title": "PTP Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "PTP Agent # $tag_agents",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agents::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p_t_p_flows.agents.output.offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "PTP-Clock relative Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p_t_p_clock",
     "select": [
      [
       { "params": [ "relative_clock_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "PTP Agent # $tag_agents",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agents::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "p_t_p_flows.agents.output.drift",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "PTP Statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Agent $tag_agents sync received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agents::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p_t_p_flows.agents.slave_statistics",
     "select": [
      [
       { "params": [ "num_syncs_received" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Agent $tag_agents follow-ups received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agents::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p_t_p_flows.agents.slave_statistics",
     "select": [
      [
       { "params": [ "num_followups_received" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Agent $tag_agents delayreq sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agents::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p_t_p_flows.agents.slave_statistics",
     "select": [
      [
       { "params": [ "num_delayreqs_sent" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Agent $tag_agents delay-resp received",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agents::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "p_t_p_flows.agents.slave_statistics",
     "select": [
      [
       { "params": [ "num_delayresps_received" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Clock States",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "PTP Clock",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "p_t_p_clock",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Genlock Audio $tag_instances",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instances::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "genlock.instances.backend.lanes.audio",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Genlock 50Hz $tag_instances",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instances::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "genlock.instances.backend.lanes.video_f50_ish",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "alias": "Genlock 59.94Hz $tag_instances",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instances::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "genlock.instances.backend.lanes.video_f59_ish",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "SDI IN Offset to PTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "SDI IN $tag_input",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "input::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "i_o_module.input.sdi.output.video.media_clock.offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "SDI Out Phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "SDI OUT $tag_output",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "output::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "i_o_module.output.sdi",
     "select": [
      [
       { "params": [ "in_phase" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  }
 ]
}