{
 "title": "Traffic [Facility]",
 "tags": [
  "Traffic",
  "Facility"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "coarse_grained_interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "blades",
    "query": "show tag values with key=\"ip\""
   }
  ]
 },
 "panels": [
  {
   "title": "Tx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TX Streams",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_ip tx_all_streams",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports.fpga_lane_statistics.tx_all_streams",
     "select": [
      [
       { "params": [ "bytes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "$tag_ip tx_frame_octetsok",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports.aggregate_traffic_statistics.tx_frame_octetsok",
     "select": [
      [
       { "params": [ "bytes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "Rx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RX Streams",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.rx_streams",
     "select": [
      [
       { "params": [ "bytes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    },
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network_interfaces.ports.aggregate_traffic_statistics.rx_frame_octetsok",
     "select": [
      [
       { "params": [ "bytes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "RX Errors",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "network_interfaces.ports.aggregate_traffic_statistics.rx_error",
     "select": [
      [
       { "params": [ "bytes_total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  },
  {
   "title": "CRC Errors",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "alias": "$tag_ip",
     "groupBy": [
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "network_interfaces.ports.aggregate_traffic_statistics.rx_crc_error",
     "select": [
      [
       { "params": [ "bytes_total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ip", "operator": "=~", "value": "/^$blades$/" }
     ]
    }
   ]
  }
 ]
}