{
 "title": "Receiver Diagnostics",
 "time": { "from": "2025-01-09T08:36:28.221Z", "to": "2025-01-09T14:36:28.221Z" },
 "templating": {
  "list": [
   {
    "name": "IP",
    "label": "IP",
    "query": "SHOW TAG VALUES with key=\"ip\""
   },
   {
    "name": "RECEIVER",
    "label": "RECEIVER",
    "query": "SHOW TAG VALUES WITH KEY=\"video_receivers\""
   },
   {
    "name": "packetstream",
    "label": "packetstream",
    "query": "SELECT distinct(\"stream\") FROM \"r_t_p_receiver.video_receivers.generic.packet_streams.sdp_a\" WHERE (\"ip\"::tag =~ /^$IP$/ AND \"video_receivers\"::tag =~ /^$RECEIVER$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
   },
   {
    "name": "packetstreamB",
    "label": "packetstream",
    "query": "SELECT distinct(\"stream\") FROM \"r_t_p_receiver.video_receivers.generic.packet_streams.sdp_b\" WHERE (\"ip\"::tag =~ /^$IP$/ AND \"video_receivers\"::tag =~ /^$RECEIVER$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
   }
  ]
 },
 "panels": [
  { "title": "Receiver $RECEIVER Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "RECEIVER" },
  {
   "title": "Video Standard",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.media_specific.output.video",
     "select": [
      [
       { "params": [ "standard" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  },
  {
   "title": "Black",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.media_specific.output.video",
     "select": [
      [
       { "params": [ "black" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  },
  {
   "title": "Timing Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.timing.target_status",
     "select": [
      [
       { "params": [ "variant" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.tracks",
     "select": [
      [
       { "params": [ "ingress" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  },
  {
   "title": "Egress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.tracks",
     "select": [
      [
       { "params": [ "egress" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  },
  {
   "title": "Stream Type",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.packet_streams.stream_parameters",
     "query": "SELECT mean(\"bytes_per_sec\") * 8 FROM \"r_t_p_receiver.packet_streams.traffic_stats\" WHERE (\"ip\"::tag =~ /^$IP$/ AND (\"packet_streams\"::tag =~ /^$packetstream$/ OR \"packet_streams\"::tag =~ /^$packetstreamB$/)) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "type" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstream$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstreamB$/" }
     ]
    }
   ]
  },
  {
   "title": "Freeze",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.media_specific.output.video",
     "select": [
      [
       { "params": [ "frozen" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  },
  {
   "title": "Target Read Delay",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.timing.target_status",
     "select": [
      [
       { "params": [ "read_delay" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  },
  {
   "title": "current_target",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.tracks",
     "select": [
      [
       { "params": [ "current_target" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  },
  {
   "title": "next_target",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.tracks",
     "select": [
      [
       { "params": [ "next_target" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  },
  {
   "title": "primary destination address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.packet_streams.stream_parameters",
     "query": "SELECT mean(\"bytes_per_sec\") * 8 FROM \"r_t_p_receiver.packet_streams.traffic_stats\" WHERE (\"ip\"::tag =~ /^$IP$/ AND (\"packet_streams\"::tag =~ /^$packetstream$/ OR \"packet_streams\"::tag =~ /^$packetstreamB$/)) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "dst_address" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstream$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstreamB$/" }
     ]
    }
   ]
  },
  {
   "title": "primary source address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.packet_streams.stream_parameters",
     "query": "SELECT mean(\"bytes_per_sec\") * 8 FROM \"r_t_p_receiver.packet_streams.traffic_stats\" WHERE (\"ip\"::tag =~ /^$IP$/ AND (\"packet_streams\"::tag =~ /^$packetstream$/ OR \"packet_streams\"::tag =~ /^$packetstreamB$/)) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "src_address" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstream$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstreamB$/" }
     ]
    }
   ]
  },
  {
   "title": "secondary destination address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.packet_streams.stream_parameters",
     "query": "SELECT mean(\"bytes_per_sec\") * 8 FROM \"r_t_p_receiver.packet_streams.traffic_stats\" WHERE (\"ip\"::tag =~ /^$IP$/ AND (\"packet_streams\"::tag =~ /^$packetstream$/ OR \"packet_streams\"::tag =~ /^$packetstreamB$/)) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "dst_address" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstream$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstreamB$/" }
     ]
    }
   ]
  },
  {
   "title": "secondary source address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.packet_streams.stream_parameters",
     "query": "SELECT mean(\"bytes_per_sec\") * 8 FROM \"r_t_p_receiver.packet_streams.traffic_stats\" WHERE (\"ip\"::tag =~ /^$IP$/ AND (\"packet_streams\"::tag =~ /^$packetstream$/ OR \"packet_streams\"::tag =~ /^$packetstreamB$/)) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "src_address" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstream$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstreamB$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.timing.read_delay.overall",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  },
  {
   "title": "Bits per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.packet_streams.traffic_stats",
     "query": "SELECT mean(\"bytes_per_sec\") * 8 FROM \"r_t_p_receiver.packet_streams.traffic_stats\" WHERE (\"ip\"::tag =~ /^$IP$/ AND (\"packet_streams\"::tag =~ /^$packetstream$/ OR \"packet_streams\"::tag =~ /^$packetstreamB$/)) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "bytes_per_sec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstream$/" },
      { "condition": "OR", "key": "packet_streams::tag", "operator": "=~", "value": "/^$packetstreamB$/" }
     ]
    }
   ]
  },
  {
   "title": "Phase offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip::tag" ], "type": "tag" },
      { "params": [ "video_receivers::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.timing.current_phase.offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  },
  {
   "title": "Phase Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ip::tag" ], "type": "tag" },
      { "params": [ "video_receivers::tag" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "r_t_p_receiver.video_receivers.generic.timing.current_phase.drift",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ip::tag", "operator": "=~", "value": "/^$IP$/" },
      { "condition": "AND", "key": "video_receivers::tag", "operator": "=~", "value": "/^$RECEIVER$/" }
     ]
    }
   ]
  }
 ]
}